name: My Workflow

on:
  push:

jobs:
  version-and-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: print node version
        run: node --version

      - name: print npm version
        run: npm --version

      - name: install dependencies
        run: npm ci
      
      - name: run tests
        run: npm test
      
      - name: docker build ci
        run: docker build -t notes-api:ci .

      